DEBUG: true
server:
  port: 8082
database:
  host: "localhost"
  port: 3306
  user: "user"
  password: "password"
  name: "iot-db"
kafka:
  host: 127.0.0.1
  port: 9092
  producer:
    topic: image-command
